### ISSUE TITLE
Not showing correct Board after Server start

### ISSUE THREAD

**Issue by MatrixSystemPVP** [ShieldCommunity/SternalBoard#49]
**Describe the bug**
After Server start the default board will be shown from config.yml, even when animated is set to true.
Only after issuing the command /sb reload it will show the correct one from animated-board.yml.

**To Reproduce**
1. Set animated to true in config.yml
2. Restart/Start the Server
3. Now you see the default board from config.yml
4. Issue the Command /sb reload
5. Now you will see the correct animated board from animated-baords.yml

**Expected behavior**
It should show the correct board at Server startup.

**Additional context**
Plugin Version: SternalBoard-2.2.0-PRE-4.jar

**Comment by xIsm4** [comment]
> ###
> [May 19, 2023](#issue-1717403426)

I will try to reproduce it, thanks for the report

**Comment by xism4** [comment]
> **Describe the bug** After Server start the default board will be shown from config.yml, even when animated is set to true. Only after issuing the command /sb reload it will show the correct one from animated-board.yml.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Set animated to true in config.yml
> 2. Restart/Start the Server
> 3. Now you see the default board from config.yml
> 4. Issue the Command /sb reload
> 5. Now you will see the correct animated board from animated-baords.yml
> 
> **Expected behavior** It should show the correct board at Server startup.
> 
> **Additional context** Plugin Version: SternalBoard-2.2.0-PRE-4.jar

Fixed on 2.2.1, i will close this,

**Comment by MatrixSystemPVP** [comment]
I've downloaded the v2.2.1 from Spigot, but still isn't fixed.
It is still showing the not Animated Scoreboard after Server start/restart.

**Comment by xism4** [comment]
> I've downloaded the v2.2.1 from Spigot, but still isn't fixed. It is still showing the not Animated Scoreboard after Server start/restart.

Try 2.2.2

**Comment by MatrixSystemPVP** [comment]
> > I've downloaded the v2.2.1 from Spigot, but still isn't fixed. It is still showing the not Animated Scoreboard after Server start/restart.
> 
> Try 2.2.2

Doesn't work. I've tried 2.2.2 and 2.2.3.

**Comment by MatrixSystemPVP** [comment]
#dump
